# Generated by Django 5.1.7 on 2025-10-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username of the user', max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price associated with the user', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Status of the user', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date when the user details were created')),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
                'ordering': ['-date'],
            },
        ),
    ]
