# Generated by Django 5.1.7 on 2025-10-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification_read_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityofficer',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for security officer', max_length=128, null=True),
        ),
    ]
