# Generated by Django 5.1.7 on 2025-11-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geofences',
            field=models.ManyToManyField(blank=True, help_text='Geofences associated with this user for alert notifications', related_name='associated_users', to='users.geofence'),
        ),
    ]
