# Generated by Django 5.1.7 on 2025-12-17 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userreply_read_by_userreply_read_timestamps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='officer',
            field=models.ForeignKey(blank=True, help_text="Security officer who reported this incident (User with role='security_officer')", limit_choices_to={'role': 'security_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_officers',
            field=models.ManyToManyField(blank=True, help_text="Security officers who should receive this notification (Users with role='security_officer')", limit_choices_to={'role': 'security_officer'}, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
