# Generated by Django 5.1.7 on 2025-12-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_incident_officer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityofficer',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Security Officer', 'verbose_name_plural': 'Security Officers'},
        ),
    ]
