# Generated by Django 5.1.7 on 2025-12-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_securityofficer_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='securityofficer',
            table='users_securityofficer',
        ),
    ]
