# Generated by Django 5.1.7 on 2025-12-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_securityofficer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number or contact information', max_length=20, null=True),
        ),
    ]
