# Generated by Django 5.1.7 on 2026-01-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='geofence_type',
            field=models.CharField(choices=[('circle', 'Circle'), ('polygon', 'Polygon')], default='circle', help_text='Type of geofence: circle or polygon', max_length=10),
        ),
    ]
