# Generated by Django 5.1.7 on 2026-01-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_geofence_geofence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Center latitude for circle geofences', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='geofence',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Center longitude for circle geofences', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='geofence',
            name='radius',
            field=models.IntegerField(blank=True, help_text='Radius in meters for circle geofences', null=True),
        ),
    ]
