# Generated by Django 5.1.7 on 2026-02-09 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_geofence_center_latitude_geofence_center_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerGeofenceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPER_ADMIN', 'SUB_ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_geofence_assignments', to=settings.AUTH_USER_MODEL)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_assignments', to='users.geofence')),
                ('officer', models.ForeignKey(limit_choices_to={'role': 'security_officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_officer_geofence_assignment',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['officer', 'is_active'], name='users_offic_officer_20b432_idx'), models.Index(fields=['geofence', 'is_active'], name='users_offic_geofenc_f62f91_idx'), models.Index(fields=['assigned_at'], name='users_offic_assigne_dca07c_idx')],
                'unique_together': {('officer', 'geofence', 'is_active')},
            },
        ),
    ]
