# Generated by Django 5.1.7 on 2026-02-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_officergeofenceassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityOfficer',
        ),
    ]
