# Generated by Django 5.1.7 on 2026-02-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_drop_securityofficer_table'),
    ]

    operations = [
    ]
