# Generated by Django 5.1.7 on 2026-02-27 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_drop_securityofficer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, help_text='Security officer assigned to this alert', limit_choices_to={'role': 'security_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='location',
            field=models.JSONField(blank=True, help_text="Location data: {'latitude': float, 'longitude': float, 'accuracy': float}", null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='message',
            field=models.TextField(blank=True, help_text='Additional message content', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='read_by',
            field=models.ManyToManyField(blank=True, help_text='Users who have read this alert', related_name='read_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='read_timestamps',
            field=models.JSONField(blank=True, default=dict, help_text="Timestamps when each user read this alert. Format: {'user_id': 'ISO_timestamp'}"),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('USER_SOS', 'User SOS Emergency'), ('OFFICER_ALERT', 'Officer Alert'), ('SYSTEM_ALERT', 'System Alert'), ('GEOFENCE_VIOLATION', 'Geofence Violation'), ('SECURITY_BREACH', 'Security Breach')], default='USER_SOS', help_text='Type of alert', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='geofence',
            field=models.ForeignKey(blank=True, help_text='Geofence associated with this alert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='users.geofence'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='geofences',
            field=models.ManyToManyField(blank=True, help_text='Legacy multiple geofences field (deprecated, use geofence instead)', related_name='legacy_alerts', to='users.geofence'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(help_text='User who created this alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'status'], name='users_alert_alert_t_0a396c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['geofence', 'created_at'], name='users_alert_geofenc_893266_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'created_at'], name='users_alert_user_id_1b1f82_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['assigned_officer', 'status'], name='users_alert_assigne_23aaf1_idx'),
        ),
    ]
