# Generated by Django 5.1.7 on 2026-03-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alert_assigned_officer_alert_location_alert_message_and_more'),
        ('users', '0025_auto_20260227_1500'),
    ]

    operations = [
    ]
