# Generated by Django 5.1.7 on 2026-03-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_merge_20260304_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
    ]
