# Generated by Django 5.1.7 on 2026-03-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_alert_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alert',
            table='users_alert',
        ),
    ]
