# Generated by Django 5.1.7 on 2025-10-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubAdminProfile',
        ),
    ]
