# Generated by Django 5.1.7 on 2025-10-28 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_subadminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_users',
            field=models.ManyToManyField(blank=True, help_text='Users who have read this notification', related_name='read_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
