# Generated by Django 5.1.7 on 2025-10-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_password_to_security_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityofficer',
            name='username',
            field=models.CharField(blank=True, help_text='Unique username for security officer', max_length=150, null=True, unique=True),
        ),
    ]
