# Generated by Django 5.1.7 on 2025-11-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_geofences',
            field=models.JSONField(blank=True, default=list, help_text='List of geofence IDs for multi-geofence notifications'),
        ),
    ]
