# Generated by Django 5.1.7 on 2025-11-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notification_target_geofences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SUB_ADMIN', 'Sub Admin'), ('USER', 'User'), ('security_officer', 'Security Officer')], default='USER', max_length=20),
        ),
    ]
