# Generated by Django 5.1.7 on 2025-11-26 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_geofences'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='geofences',
            field=models.ManyToManyField(blank=True, help_text='Geofences associated with this alert. All users, subadmins, and security officers associated with these geofences will see this alert.', related_name='alerts', to='users.geofence'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='geofence',
            field=models.ForeignKey(blank=True, help_text='Legacy single geofence field (deprecated, use geofences instead)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_alerts', to='users.geofence'),
        ),
    ]
