# Generated by Django 5.1.7 on 2025-11-29 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alert_geofences_alter_alert_geofence'),
        ('users_profile', '0018_add_security_officer_to_live_location_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreply',
            name='read_by',
            field=models.ManyToManyField(blank=True, help_text='Admins, sub-admins, and security officers who have read this reply', related_name='read_user_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreply',
            name='read_timestamps',
            field=models.JSONField(blank=True, default=dict, help_text="Timestamps when each user read this reply. Format: {'user_id': 'ISO_timestamp'}"),
        ),
        migrations.AddField(
            model_name='userreply',
            name='sos_event',
            field=models.ForeignKey(blank=True, help_text='Related SOS event if this reply is about an SOS alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_replies', to='users_profile.sosevent'),
        ),
    ]
