# Generated by Django 5.1.7 on 2025-10-13 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.FloatField(help_text='Latitude coordinate')),
                ('location_long', models.FloatField(help_text='Longitude coordinate')),
                ('message', models.TextField(blank=True, help_text='Optional message from the user', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Alert',
                'verbose_name_plural': 'SOS Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
