# Generated by Django 5.1.7 on 2025-12-17 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0002_officerprofile_battery_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='officer',
            field=models.ForeignKey(blank=True, help_text="Security officer assigned to this case (User with role='security_officer')", limit_choices_to={'role': 'security_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='officer',
            field=models.ForeignKey(blank=True, help_text="Security officer who reported this incident (User with role='security_officer')", limit_choices_to={'role': 'security_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_app_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='officer',
            field=models.ForeignKey(help_text="Security officer who should receive this notification (User with role='security_officer')", limit_choices_to={'role': 'security_officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='security_app_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='officer',
            field=models.OneToOneField(help_text="Security officer user (User with role='security_officer')", limit_choices_to={'role': 'security_officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, help_text="Security officer assigned to this SOS alert (User with role='security_officer')", limit_choices_to={'role': 'security_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_app_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
