# Generated by Django 5.1.7 on 2026-01-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0003_alter_case_officer_alter_incident_officer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number or mobile phone for the security officer', max_length=20, null=True),
        ),
    ]
