# Generated by Django 5.1.7 on 2026-01-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0004_officerprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='alert_type',
            field=models.CharField(default='security', max_length=20),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
