# Generated by Django 5.1.7 on 2026-02-04 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0005_sosalert_alert_type_sosalert_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='affected_users_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users affected by this area-based alert'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry time for area-based alerts', null=True),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether push notifications have been sent for this alert'),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when notifications were sent', null=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='alert_type',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('security', 'Security'), ('general', 'General'), ('area_user_alert', 'Area User Alert')], default='security', max_length=20),
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Last known latitude of the user', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Last known longitude of the user', max_digits=11)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters above sea level', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in meters per second', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees (0-360)', null=True)),
                ('location_timestamp', models.DateTimeField(help_text='Timestamp when the GPS location was recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User whose location is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='last_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location',
                'verbose_name_plural': 'User Locations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
