# Generated by Django 5.1.7 on 2026-02-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0003_remove_created_by_role_default'),
        ('security_app', '0006_sosalert_affected_users_count_sosalert_expires_at_and_more'),
    ]

    operations = [
    ]
