# Generated by Django 5.1.7 on 2026-02-11 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0007_merge_20260211_1159'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Current latitude')),
                ('longitude', models.FloatField(help_text='Current longitude')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sos_alert', models.OneToOneField(help_text='SOS alert this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to='security_app.sosalert')),
                ('user', models.ForeignKey(help_text='Alert creator who owns this location', on_delete=django.db.models.deletion.CASCADE, related_name='alert_live_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Alert Live Location',
                'verbose_name_plural': 'SOS Alert Live Locations',
            },
        ),
    ]
