# Generated by Django 5.1.7 on 2026-02-11 07:31

from django.db import migrations, models


def set_default_created_by_role(apps, schema_editor):
    """Set default created_by_role for existing records that have it NULL"""
    SOSAlert = apps.get_model('security_app', 'SOSAlert')
    
    # Update records where created_by_role is NULL or empty
    SOSAlert.objects.filter(
        models.Q(created_by_role__isnull=True) | models.Q(created_by_role='')
    ).update(created_by_role='USER')


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0008_livelocation'),
    ]

    operations = [
        migrations.RunPython(set_default_created_by_role, migrations.RunPython.noop),
    ]
