# Generated by Django 5.2.7 on 2025-10-16 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_case'),
        ('users', '0006_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_cases', to='users.securityofficer'),
        ),
    ]
