# Generated by Django 5.1.7 on 2025-10-08 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(help_text='Phone number or contact info', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_officers', to='users.geofence')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'SUB_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_officers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_officers', to='users.organization')),
            ],
            options={
                'verbose_name': 'Security Officer',
                'verbose_name_plural': 'Security Officers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NORMAL', 'Normal'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_type', models.CharField(choices=[('ALL_OFFICERS', 'All Officers'), ('GEOFENCE_OFFICERS', 'Geofence Officers'), ('SPECIFIC_OFFICERS', 'Specific Officers'), ('SUB_ADMIN', 'Sub Admin Only')], default='ALL_OFFICERS', max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'SUB_ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.organization')),
                ('target_geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.geofence')),
                ('target_officers', models.ManyToManyField(blank=True, related_name='received_notifications', to='users.securityofficer')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('SECURITY_BREACH', 'Security Breach'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('EMERGENCY', 'Emergency'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], default='SUSPICIOUS_ACTIVITY', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('location', models.JSONField(default=dict, help_text='GPS coordinates and location details')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='users.geofence')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='users.securityofficer')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
    ]
