# Generated by Django 5.1.7 on 2025-10-10 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to send discount to', max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent')], default='PENDING', help_text='Status of the discount email', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.ForeignKey(help_text='Promo code to send', on_delete=django.db.models.deletion.CASCADE, related_name='discount_emails', to='users.promocode')),
            ],
            options={
                'verbose_name': 'Discount Email',
                'verbose_name_plural': 'Discount Emails',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'discount_code')},
            },
        ),
    ]
