# Generated by Django 5.1.7 on 2025-10-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_discountemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the user who replied', max_length=254)),
                ('message', models.TextField(help_text='Reply message from the user')),
                ('date_time', models.DateTimeField(auto_now_add=True, help_text='Date and time when the reply was received')),
            ],
            options={
                'verbose_name': 'User Reply',
                'verbose_name_plural': 'User Replies',
                'ordering': ['-date_time'],
            },
        ),
    ]
