# Generated by Django 5.1.7 on 2025-11-19 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sosevent',
            name='audio_recording_url',
            field=models.URLField(blank=True, help_text='URL to audio recording (Premium feature)', null=True),
        ),
        migrations.AddField(
            model_name='sosevent',
            name='cloud_backup_url',
            field=models.URLField(blank=True, help_text='URL to cloud backup of SOS evidence (Premium feature)', null=True),
        ),
        migrations.AddField(
            model_name='sosevent',
            name='is_premium_event',
            field=models.BooleanField(default=False, help_text='Whether this SOS event used premium features'),
        ),
        migrations.AddField(
            model_name='sosevent',
            name='video_recording_url',
            field=models.URLField(blank=True, help_text='URL to video recording (Premium feature)', null=True),
        ),
        migrations.AlterField(
            model_name='sosevent',
            name='status',
            field=models.CharField(choices=[('triggered', 'Triggered'), ('sms_sent', 'SMS Sent'), ('police_called', 'Police Called'), ('geofence_alerted', 'Geofence Alerted'), ('response_center_notified', 'Response Center Notified'), ('audio_recording', 'Audio Recording'), ('video_recording', 'Video Recording'), ('resolved', 'Resolved')], default='triggered', help_text='Current status of the SOS event', max_length=30),
        ),
        migrations.CreateModel(
            name='CommunityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Alert message')),
                ('location', models.JSONField(help_text='Location where alert was sent (longitude, latitude)')),
                ('radius_meters', models.IntegerField(default=500, help_text='Alert radius in meters')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_premium_alert', models.BooleanField(default=False, help_text='Whether this is a premium alert (reaches verified responders)')),
                ('user', models.ForeignKey(help_text='User who sent the alert', on_delete=django.db.models.deletion.CASCADE, related_name='community_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Alert',
                'verbose_name_plural': 'Community Alerts',
                'db_table': 'users_community_alert',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the geofence (e.g., 'Home', 'Work')", max_length=200)),
                ('center_location', models.JSONField(help_text='Center point of geofence (longitude, latitude)')),
                ('radius_meters', models.IntegerField(default=100, help_text='Radius of the geofence in meters')),
                ('alert_on_entry', models.BooleanField(default=True, help_text='Alert when user enters the geofence')),
                ('alert_on_exit', models.BooleanField(default=True, help_text='Alert when user exits the geofence')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the geofence is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who owns this geofence', on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geofence',
                'verbose_name_plural': 'Geofences',
                'db_table': 'users_profile_geofence',
            },
        ),
        migrations.CreateModel(
            name='LiveLocationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the live sharing session expires')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the session is currently active')),
                ('current_location', models.JSONField(blank=True, help_text='Current location (longitude, latitude)', null=True)),
                ('shared_with', models.ManyToManyField(help_text='Users who can see this live location', related_name='shared_locations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User sharing their location', on_delete=django.db.models.deletion.CASCADE, related_name='live_location_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Location Share',
                'verbose_name_plural': 'Live Location Shares',
                'db_table': 'users_live_location_share',
                'ordering': ['-started_at'],
            },
        ),
    ]
