# Generated by Django 5.1.7 on 2025-11-25 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0002_sosevent_audio_recording_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the chat group', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the group', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created the group', on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_groups', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(help_text='Members of the chat group', related_name='chat_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Group',
                'verbose_name_plural': 'Chat Groups',
                'db_table': 'users_chat_group',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Message text content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(help_text='Chat group this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users_profile.chatgroup')),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'users_chat_message',
                'ordering': ['created_at'],
            },
        ),
    ]
