# Generated by Django 5.1.7 on 2025-11-25 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0003_chatgroup_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Admin of the group (can be different from creator)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chat_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
