# Generated by Django 5.1.7 on 2025-11-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0007_remove_sosevent_audio_recording_url_and_more'),
    ]

    operations = [
    ]
