# Generated by Django 5.1.7 on 2025-11-26 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0008_auto_20251126_0607'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofence',
            name='user',
            field=models.ForeignKey(help_text='User who owns this geofence', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_geofences', to=settings.AUTH_USER_MODEL),
        ),
    ]
