# Generated by Django 5.1.7 on 2025-11-26 09:10

from django.db import migrations, connection


FIELDS_TO_REMOVE = [
    'audio_recording_url',
    'cloud_backup_url',
    'is_premium_event',
    'video_recording_url',
]


def remove_fields_if_table_exists(apps, schema_editor):
    db_table = 'users_profile_sosevent'
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_name = %s
            )
        """, [db_table])
        table_exists = cursor.fetchone()[0]

        if not table_exists:
            print(f"[users_profile] Skipping column removal; table {db_table} does not exist.")
            return

        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = %s
        """, [db_table])
        existing_columns = {row[0] for row in cursor.fetchall()}

        for field in FIELDS_TO_REMOVE:
            if field in existing_columns:
                cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN IF EXISTS {field}')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0009_remove_sosevent_audio_recording_url_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_fields_if_table_exists, noop_reverse),
    ]
