# Generated by Django 5.1.7 on 2025-11-27 08:55

from django.db import migrations, connection


FIELDS_TO_REMOVE = [
    'audio_recording_url',
    'cloud_backup_url',
    'is_premium_event',
    'video_recording_url',
]


def remove_fields_if_exist(apps, schema_editor):
    """
    Safely remove fields from SOSEvent model only if they exist in the database.
    This handles the case where fields were already removed by a previous migration.
    """
    db_table = 'users_profile_sosevent'
    db_backend = connection.vendor

    with connection.cursor() as cursor:
        # Check if table exists - different SQL for different databases
        if db_backend == 'postgresql':
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_name = %s
                )
            """, [db_table])
            table_exists = cursor.fetchone()[0]
        elif db_backend == 'sqlite':
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=%s", [db_table])
            table_exists = cursor.fetchone() is not None
        else:
            # For other databases, skip the operation
            print(f"[users_profile] Unsupported database backend {db_backend}, skipping field removal")
            return

        if not table_exists:
            print(f"[users_profile] Skipping field removal; table {db_table} does not exist.")
            return

        # Get existing columns - different SQL for different databases
        if db_backend == 'postgresql':
            cursor.execute("""
                SELECT column_name
                FROM information_schema.columns
                WHERE table_name = %s
            """, [db_table])
            existing_columns = {row[0] for row in cursor.fetchall()}
        elif db_backend == 'sqlite':
            cursor.execute(f"PRAGMA table_info({db_table})")
            # For SQLite, column name is at index 1
            rows = cursor.fetchall()
            existing_columns = {row[1] for row in rows}
        else:
            print(f"[users_profile] Unsupported database backend {db_backend}, skipping field removal")
            return

        # Remove fields that exist
        for field in FIELDS_TO_REMOVE:
            if field in existing_columns:
                if db_backend == 'postgresql':
                    cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN IF EXISTS {field}')
                elif db_backend == 'sqlite':
                    cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN {field}')
                print(f"[users_profile] Dropped field {field} from {db_table}")
            else:
                print(f"[users_profile] Field {field} does not exist in {db_table}, skipping")


def noop_reverse(apps, schema_editor):
    """No reverse operation needed since we're removing fields."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0011_populate_chatmessage_file_name'),
    ]

    operations = [
        migrations.RunPython(remove_fields_if_exist, noop_reverse),
    ]
