# Generated by Django 5.1.7 on 2025-11-29 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userreply_read_by_userreply_read_timestamps_and_more'),
        ('users_profile', '0018_add_security_officer_to_live_location_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='livelocationshare',
            name='user_or_security_officer_required',
        ),
        migrations.AddField(
            model_name='sosevent',
            name='read_by',
            field=models.ManyToManyField(blank=True, help_text='Admins, sub-admins, and security officers who have read this SOS event', related_name='read_sos_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sosevent',
            name='read_timestamps',
            field=models.JSONField(blank=True, default=dict, help_text="Timestamps when each user read this SOS event. Format: {'user_id': 'ISO_timestamp'}"),
        ),
        migrations.AddConstraint(
            model_name='livelocationshare',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('security_officer__isnull', True), ('user__isnull', False)), models.Q(('security_officer__isnull', False), ('user__isnull', True)), _connector='OR'), name='user_or_security_officer_required'),
        ),
    ]
