# Generated by Django 5.1.7 on 2025-12-17 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0021_remove_user_profile_geofence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='livelocationshare',
            name='security_officer',
            field=models.ForeignKey(blank=True, help_text="Security officer sharing their location (User with role='security_officer', null if user is set)", limit_choices_to={'role': 'security_officer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_live_location_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
