# Generated by Django 5.1.7 on 2025-10-30 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_notification_read_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='users.securityofficer')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_duty', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.securityofficer')),
            ],
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_app_alerts', to='users.securityofficer')),
                ('geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='users.geofence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_app_sos_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Alert',
                'verbose_name_plural': 'SOS Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('sos_alert', 'SOS Alert'), ('case_assigned', 'Case Assigned'), ('case_resolved', 'Case Resolved'), ('system', 'System')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='security_app.case')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.securityofficer')),
                ('sos_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='security_app.sosalert')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_long', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('manual', 'Manual')], default='resolved', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='security_app.case')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='users.securityofficer')),
                ('sos_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='security_app.sosalert')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='sos_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='security_app.sosalert'),
        ),
    ]
