# Generated by Django 5.1.7 on 2025-11-24 08:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Alert message')),
                ('location', models.JSONField(help_text='Location where alert was sent (longitude, latitude)')),
                ('radius_meters', models.IntegerField(default=500, help_text='Alert radius in meters')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_premium_alert', models.BooleanField(default=False, help_text='Whether this is a premium alert (reaches verified responders)')),
                ('user', models.ForeignKey(help_text='User who sent the alert', on_delete=django.db.models.deletion.CASCADE, related_name='community_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Alert',
                'verbose_name_plural': 'Community Alerts',
                'db_table': 'users_community_alert',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the geofence (e.g., 'Home', 'Work')", max_length=200)),
                ('center_location', models.JSONField(help_text='Center point of geofence (longitude, latitude)')),
                ('radius_meters', models.IntegerField(default=100, help_text='Radius of the geofence in meters')),
                ('alert_on_entry', models.BooleanField(default=True, help_text='Alert when user enters the geofence')),
                ('alert_on_exit', models.BooleanField(default=True, help_text='Alert when user exits the geofence')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the geofence is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who owns this geofence', on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Geofence',
                'verbose_name_plural': 'Geofences',
                'db_table': 'users_profile_geofence',
            },
        ),
        migrations.CreateModel(
            name='LiveLocationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the live sharing session expires')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the session is currently active')),
                ('current_location', models.JSONField(blank=True, help_text='Current location (longitude, latitude)', null=True)),
                ('shared_with', models.ManyToManyField(help_text='Users who can see this live location', related_name='shared_locations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User sharing their location', on_delete=django.db.models.deletion.CASCADE, related_name='live_location_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Location Share',
                'verbose_name_plural': 'Live Location Shares',
                'db_table': 'users_live_location_share',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(blank=True, help_text='Location where SOS was triggered (longitude, latitude)', null=True)),
                ('status', models.CharField(choices=[('triggered', 'Triggered'), ('sms_sent', 'SMS Sent'), ('police_called', 'Police Called'), ('geofence_alerted', 'Geofence Alerted'), ('response_center_notified', 'Response Center Notified'), ('audio_recording', 'Audio Recording'), ('video_recording', 'Video Recording'), ('resolved', 'Resolved')], default='triggered', help_text='Current status of the SOS event', max_length=30)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the SOS event')),
                ('audio_recording_url', models.URLField(blank=True, help_text='URL to audio recording (Premium feature)', null=True)),
                ('video_recording_url', models.URLField(blank=True, help_text='URL to video recording (Premium feature)', null=True)),
                ('cloud_backup_url', models.URLField(blank=True, help_text='URL to cloud backup of SOS evidence (Premium feature)', null=True)),
                ('is_premium_event', models.BooleanField(default=False, help_text='Whether this SOS event used premium features')),
                ('user', models.ForeignKey(help_text='User who triggered the SOS', on_delete=django.db.models.deletion.CASCADE, related_name='sos_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Event',
                'verbose_name_plural': 'SOS Events',
                'db_table': 'users_sos_event',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.CharField(help_text='Unique identifier for the community', max_length=100)),
                ('community_name', models.CharField(help_text='Name of the community', max_length=200)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(help_text='User who is a member of the community', on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Membership',
                'verbose_name_plural': 'Community Memberships',
                'db_table': 'users_community_membership',
                'unique_together': {('user', 'community_id')},
            },
        ),
        migrations.CreateModel(
            name='FamilyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Family contact's name", max_length=150)),
                ('phone', models.CharField(help_text="Family contact's phone number", max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('relationship', models.CharField(blank=True, help_text="Relationship to the user (e.g., 'Spouse', 'Parent', 'Sibling')", max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary emergency contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this family contact', on_delete=django.db.models.deletion.CASCADE, related_name='family_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Contact',
                'verbose_name_plural': 'Family Contacts',
                'db_table': 'users_family_contact',
                'unique_together': {('user', 'phone')},
            },
        ),
    ]
