# Generated by Django 5.1.7 on 2025-11-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0005_chatmessage_file_chatmessage_file_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sosevent',
            table='users_profile_sosevent',
        ),
    ]
