# Generated by Django 5.1.7 on 2025-11-26 06:07

from django.db import migrations, connection


def remove_fields_if_exist(apps, schema_editor):
    """
    Safely remove fields from SOSEvent model only if they exist in the database.
    """
    db_table = 'users_profile_sosevent'
    fields_to_remove = [
        'audio_recording_url',
        'cloud_backup_url',
        'is_premium_event',
        'video_recording_url'
    ]
    
    with connection.cursor() as cursor:
        # Get existing columns
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = %s
        """, [db_table])
        existing_columns = {row[0] for row in cursor.fetchall()}
        
        # Remove only columns that exist
        for field_name in fields_to_remove:
            if field_name in existing_columns:
                try:
                    cursor.execute(f'ALTER TABLE {db_table} DROP COLUMN IF EXISTS {field_name}')
                except Exception as e:
                    # If column doesn't exist or can't be dropped, continue
                    print(f"Warning: Could not remove column {field_name}: {e}")


def reverse_operation(apps, schema_editor):
    """
    Reverse operation - we don't need to recreate these fields.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0006_alter_sosevent_table'),
    ]

    operations = [
        migrations.RunPython(remove_fields_if_exist, reverse_operation),
    ]
