# Generated by Django 5.1.7 on 2025-11-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0011_populate_chatmessage_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosevent',
            name='audio_recording_url',
        ),
        migrations.RemoveField(
            model_name='sosevent',
            name='cloud_backup_url',
        ),
        migrations.RemoveField(
            model_name='sosevent',
            name='is_premium_event',
        ),
        migrations.RemoveField(
            model_name='sosevent',
            name='video_recording_url',
        ),
    ]
