# Generated by Django 5.1.7 on 2025-12-01 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alert_geofences_alter_alert_geofence'),
        ('users_profile', '0018_add_security_officer_to_live_location_share'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='livelocationshare',
            name='user_or_security_officer_required',
        ),
        migrations.AddConstraint(
            model_name='livelocationshare',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('security_officer__isnull', True), ('user__isnull', False)), models.Q(('security_officer__isnull', False), ('user__isnull', True)), _connector='OR'), name='user_or_security_officer_required'),
        ),
    ]
