# Generated by Django 5.1.7 on 2025-12-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_profile', '0020_fix_sos_status_field_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geofence',
        ),
    ]
